# coding: utf-8

GUILD_NAME_EMPTY = 1
GUILD_KCION_NOT_ENOUGH = 2
GUILD_GOLD_NOT_ENOUGH = 3
GUILD_JOINED_EXISTS = 4
GUILD_NOT_EXISTS = 5
GUILD_IS_FULL = 6
REQUEST_MEMBER_NOT_EXISTS = 7
USER_IS_A_GUILD_MEMBER = 8
NOT_HAS_GUILD_PERM = 9
NOT_HAS_APPLY_REQUEST = 10
PERM_RANGE_OVERFLOW = 11

CREATE_GUILD_COST_KCOIN = 50
CREATE_GUILD_COST_GOLD = 500
