# coding: utf-8


ENERGY_HEAL_TIME = 600
ENERGY_HEAL_UNIT = 1

USER_EXPENSE_MASTER_UP = 'master_up'

USER_EXPENSE_INDEX = {
    USER_EXPENSE_MASTER_UP: 1,
}
USER_EXPENSE_MAP = {
    1: USER_EXPENSE_MASTER_UP,
}
