# coding: utf-8


GOLD_NOT_ENOUGH = 1
KCOIN_NOT_ENOUGH = 2

HERO_NOT_EXISTS = 3
HERO_ELEMENTS_NOT_ENOUGH = 4
HERO_RESOLVE_NO_FREE_TIMES = 5
HERO_RESOLVE_IN_TEAM = 6
HERO_NOT_MAX_LEVEL = 7
HERO_IS_MAX_LEVEL = 8
HERO_MERGE_IS_LOCKING = 9
HERO_MERGE_IN_TEAM = 10
HERO_CAN_NOT_EATEN_SELL = 11
HERO_CAN_NOT_EVOLUTION = 12
HERO_SELL_IN_TEAM = 13
HERO_SELL_IS_LOCKING = 14
HERO_RESOLVE_IS_LOCKING = 16

EQUIP_ST_MAX_LEVEL = 17
EQUIP_ST_IN_CD_TIME = 27
EQUIP_SELL_IN_TEAM = 19
EQUIP_RESOLVE_IN_TEAM = 20
EQUIP_NOT_EXISTS = 23
EQUIP_ELEMENTS_NOT_ENOUGH = 24

HERO_JOB_CAN_NOT_EVOLUTION = 25
HERO_JOB_ELEMENTS_NOT_ENOUGH = 26

GOBLIN_MASTER_IS_MAX_LEVEL = 28
GOBLIN_MASTER_UP_ENOUGH_TIMES = 29
GOBLIN_FORGE_ENOUGH_TIMES = 30

GOBLIN_NOT_EXISTS = 31
GOBLIN_IS_USED = 32
GOBLIN_CAN_NOT_EATEN = 33
GOBLIN_IS_MAX_LEVEL = 34
GOBLIN_CAN_NOT_EQUIP = 35

ARENA_NOT_ENOUGH_LEVEL = 36
ARENA_FIGHT_IN_CD_TIME = 37
ARENA_AWARD_HAS_NO_AWARD = 38
ARENA_AWARD_HAS_BEEN_RECEIVE = 39
ARENA_TODAY_ENOUGH_BATTLE_TIMES = 40

ADVEN_FIGHT_NOT_ENOUGH_ENERGY = 0
