# coding: utf-8


EQUIP_TEAM_POS_KEYS = ('pos0', 'pos1', 'pos2', 'pos3', 'pos4', 'pos5', 'pos6', 'pos7')

EQUIP_FROM_INIT = 0
EQUIP_FROM_STAGE = 1
EQUIP_FROM_MERGE = 2
EQUIP_FROM_ADMIN = 3
EQUIP_FROM_ARENA = 4

EQUIP_ST_CD_MAX_MINUTE = 10
EQUIP_ST_CD_SECOND = 60

EQUIP_ABILITY_NONE = 0
EQUIP_ABILITY_NATK = 1
EQUIP_ABILITY_NDEF = 2
EQUIP_ABILITY_MATK = 3
EQUIP_ABILITY_MDEF = 4
EQUIP_ABILITY_HP = 5
EQUIP_ABILITY_NONE_ATTR = None
EQUIP_ABILITY_NATK_ATTR = 'natk'
EQUIP_ABILITY_NDEF_ATTR = 'ndef'
EQUIP_ABILITY_MATK_ATTR = 'matk'
EQUIP_ABILITY_MDEF_ATTR = 'mdef'
EQUIP_ABILITY_HP_ATTR = 'hp'

EQUIP_ABILITY_ATTRS = (
    EQUIP_ABILITY_NATK_ATTR,
    EQUIP_ABILITY_NDEF_ATTR,
    EQUIP_ABILITY_MATK_ATTR,
    EQUIP_ABILITY_MDEF_ATTR,
    EQUIP_ABILITY_HP_ATTR,
)
EQUIP_ABILITY_DATA = {
    EQUIP_ABILITY_NONE: EQUIP_ABILITY_NONE_ATTR,
    EQUIP_ABILITY_NATK: EQUIP_ABILITY_NATK_ATTR,
    EQUIP_ABILITY_NDEF: EQUIP_ABILITY_NDEF_ATTR,
    EQUIP_ABILITY_MATK: EQUIP_ABILITY_MATK_ATTR,
    EQUIP_ABILITY_MDEF: EQUIP_ABILITY_MDEF_ATTR,
    EQUIP_ABILITY_HP: EQUIP_ABILITY_HP_ATTR,
}

EQUIP_SORT_NONE = 0
EQUIP_SORT_WEAPON = 1
EQUIP_SORT_MAGIC = 2
EQUIP_SORT_DECOR = 3
EQUIP_SORT_HEAD = 4
EQUIP_SORT_BODY = 5
EQUIP_SORT_LEGS = 6
EQUIP_SORT_NONE_KEY = 'none'
EQUIP_SORT_WEAPON_KEY = 'weapon'
EQUIP_SORT_MAGIC_KEY = 'magic'
EQUIP_SORT_DECOR_KEY = 'decor'
EQUIP_SORT_HEAD_KEY = 'head'
EQUIP_SORT_BODY_KEY = 'body'
EQUIP_SORT_LEGS_KEY = 'legs'

EQUIP_TEAM_WHERE_KEYS = (
    EQUIP_SORT_WEAPON_KEY,
    EQUIP_SORT_MAGIC_KEY,
    EQUIP_SORT_DECOR_KEY,
    EQUIP_SORT_HEAD_KEY,
    EQUIP_SORT_BODY_KEY,
    EQUIP_SORT_LEGS_KEY,
)
EQUIP_SORT_WHERES = {
    EQUIP_SORT_NONE: EQUIP_SORT_NONE_KEY,
    EQUIP_SORT_WEAPON: EQUIP_SORT_WEAPON_KEY,
    EQUIP_SORT_MAGIC: EQUIP_SORT_MAGIC_KEY,
    EQUIP_SORT_DECOR: EQUIP_SORT_DECOR_KEY,
    EQUIP_SORT_HEAD: EQUIP_SORT_HEAD_KEY,
    EQUIP_SORT_BODY: EQUIP_SORT_BODY_KEY,
    EQUIP_SORT_LEGS: EQUIP_SORT_LEGS_KEY,
}

EQUIP_BIRTH_INIT = {
    'level': 1,
    'gold': 0,
    'matk': 0,
    'mdef': 0,
    'natk': 0,
    'ndef': 0,
    'hp': 0,
}

