# coding: utf-8

import opp_match
import effect_range
import disaster
import buff

NORMAL_ATTACK = 1
MAGIC_ATTACK = 2
CURE_ATTACK = 4
REVIVAL_ATTACK = 5

TEAMMATE = 1
OPPONENT = 2
BOTH_TARGET = TEAMMATE | OPPONENT

COST_ALL_ANGER = -1

SKILL_BUFF = 'buff'
BUFF_HP_TOP = 1
BUFF_RAGE = 2
BUFF_HP = 3
BUFF_NORMAL_ATK = 4
BUFF_MAGIC_ATK = 5
BUFF_NORMAL_DEF = 6
BUFF_MAGIC_DEF = 7
BUFF_HIT = 8
BUFF_DODGE = 9
BUFF_STORM_HIT = 10
BUFF_STORM_HURT = 11
BUFF_STORM_HOLDOUT = 12
BUFF_FINAL_HURT = 13
BUFF_DEAD_SUMMON = 14
BUFF_DIE_SUMMON = 15
BUFF_CYCLE_SUMMON = 16
BUFF_TWINING = 17
BUFF_SILENCE = 18
BUFF_DIZZINESS = 19
BUFF_UNBEATABLE = 20
BUFF_ARMOR = 21

def atk_distance(x, y):
    """
    """

    return x / 2, y / 2
