# coding: utf-8

EFFECT_GLOBAL = 'global'
EFFECT_TEAM = 'team'
EFFECT_AGENT = 'agent'

EFFECT_MAGICK_ATTACK = 1
EFFECT_NORMAL_ATTACK = 2
EFFECT_MAGICK_DEFEND = 3
EFFECT_NORMAL_DEFEND = 4
EFFECT_STORM_HIT = 5
EFFECT_RELEASE_RAGE = 6
EFFECT_RAGE = 7
EFFECT_HP = 8
