# coding: utf-8


HERO_RESOLVE_DAILY_TOP = 10

HERO_MERGE_COST = 100
HERO_MERGE_SAME_JOB_EXP_ADDITION = 1.2
HERO_MULTIPLE_MERGE_TYPE = [1, 1.3, 1.5]
HERO_MERGE_TYPE_NORMAL = 0
HERO_MERGE_TYPE_BIG = 1
HERO_MERGE_TYPE_SUPER = 2

HERO_MERGE_ACCIDENT = (0, 100)
HERO_MERGE_ACCIDENT_LIMIT = 15
HERO_MERGE_BIG_WEIGHT = 0.67
HERO_MERGE_PUREBRED = 1.5
HERO_MERGE_COST = 100

HERO_TEAM_SEQ = [0, 1, 2, 3, 4, 5, 6, 7]
HERO_TEAM_SEQ_GROUP = [3]
TEAM_MEMBER_DEFAULTS = {
    'null': None
}

HERO_FROM_INIT = 0
HERO_FROM_STAGE = 1
HERO_FROM_EVOLUTION = 2
HERO_FROM_ADMIN = 3
HERO_FROM_ARENA = 4

